supabase:
  url: null
  key: null
  url_env: SUPABASE_DEV_URL
  key_env: SUPABASE_DEV_KEY

llm:
  provider: deepseek
  model: deepseek-chat
  base_url: https://api.deepseek.com
  api_key: null
  api_key_env: DEEPSEEK_API_KEY
  max_tokens: 256

news:
  provider: coindesk
  api_key: null
  api_key_env: COINDESK_API_KEY
  categories: []

indicators:
  exchange_id: binance
  timeframe: 1h
  rsi_period: 14
  sma_fast: 50
  sma_slow: 200

generation:
  per_agent_limit: null
  max_tokens: 256

backfill:
  n_rounds: 3
  timeframe: 1h
  ingest_limit: 2
  quote: USDT
  min_events_per_round: 0

cron:
  freq: 1h
  eager_first_run: false
  jitter_seconds: 0
  ingest_before_backfill: true